version: "3.9"
services:
  application:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - MONGOURI=${MONGOURI}
      - RABBITMQ_ADDR=${RABBITMQ_ADDR}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python # TODO fix
