apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-client-actions-deployment
  labels:
    app: mqtt-client-actions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqtt-client-actions
  template:
    metadata:
      labels:
        app: mqtt-client-actions
    spec:
      containers:
        - name: mqtt-client-actions-application
          image: d3lta12/mqtt-client-actions-application:public
          imagePullPolicy: Always
          env:
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: MONGOURI
            - name: RABBITMQ_ADDR
              value: "mqtt-controller-comms-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_CONTROLLER_QUEUE
              value: "controller_messages"
            - name: RABBITMQ_CONFIG_QUEUE
              value: "action_messages"
            # TODO fix PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION env var workaround
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: "python"
