apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-reverse-proxy-deployment
  labels:
    app: mqtt-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-reverse-proxy
  template:
    metadata:
      labels:
        app: mqtt-reverse-proxy
    spec:
      containers:
        - name: mqtt-reverse-proxy-nginx
          image: d3lta12/mqtt-reverse-proxy-nginx:public
          imagePullPolicy: Always
          ports:
            - containerPort: 1883
            - containerPort: 9001
          env:
            - name: MQTT_AUTH_HOST
              value: ""
            - name: MQTT_AUTH_PORT
              value: "5000"
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_WS_PORT
              value: "9001"
