apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment # TODO rename deployment and service to match convention
  labels:
    app: controller
spec:
  replicas: 1 # TODO make sure any controller can check for server and add client password
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: mqtt-controller-application
          image: d3lta12/mqtt-controller-application:public
          imagePullPolicy: Always
          ports:
            - containerPort: 10080
          env:
            - name: MONGOURI
              value: ""
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "10080"
            - name: REDIS_ADDR
              value: "mqtt-server-cache-service"
