---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqtt-controller
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mqtt-controller-role
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "namespaces", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mqtt-controller-role-binding
subjects:
  - kind: ServiceAccount
    name: mqtt-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: mqtt-controller-role
  apiGroup: rbac.authorization.k8s.io
