apiVersion: v1
kind: Service
metadata:
  name: mqtt-controller-service
spec:
  type: LoadBalancer
  selector:
    app: mqtt-controller
  ports:
    - name: mqtt-controller-endpoint
      protocol: TCP
      port: 18080
      targetPort: 18080
