apiVersion: v1
kind: Service
metadata:
  name: controller-service
spec:
  type: LoadBalancer
  selector:
    app: controller
  ports:
    - name: controller-endpoint
      protocol: TCP
      port: 10080
      targetPort: 10080
