apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-controller-deployment
  labels:
    app: mqtt-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mqtt-controller
  template:
    metadata:
      labels:
        app: mqtt-controller
    spec:
      containers:
        - name: mqtt-controller-application
          image: d3lta12/mqtt-controller-application:public
          imagePullPolicy: Always
          ports:
            - containerPort: 10080
          env:
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: MONGOURI
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "10080"
            - name: RABBITMQ_ADDR
              value: "mqtt-controller-comms-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_CONTROLLER_QUEUE
              value: "controller_messages"
            - name: RABBITMQ_ACTION_QUEUE
              value: "action_messages"
            # TODO fix PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION env var workaround
            - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
              value: "python"
