version: "3.9"
services:
  application:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "10080:10080"
      # - "443:443" # TODO TLS support
    environment:
      - MONGOURI=${MONGOURI}
      - KUBECONFIG=${KUBECONFIG}
      - HOST="0.0.0.0"
      - PORT=10080
