version: "3.9"
services:
  rabbitmq:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "1883:1883"
      # - "15672:15672"  # management port
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
networks:
  default:
    name: rabbitnet
    external: true