version: "3.9"
services:
  eclipse-mosquitto:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "1883:1883"
      - "9001:9001"
      - "9443:9443"
    environment:
      - PASSWD_FILE=/password
      - IP_ADDR=0.0.0.0
      - PORT=9443
      - CERT=cert.pem
      - KEY=key.pem
    # volumes:
    #   - ./config:/mosquitto/config/.
