apiVersion: v1
kind: Service
metadata:
  name: mqtt-server-service
spec:
  type: LoadBalancer
  selector:
    app: mqtt-server
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: mqtt-websocket
      protocol: TCP
      port: 9001
      targetPort: 9001
