apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  type: LoadBalancer
  selector:
    app: mqtt
  ports:
    - name: mqtt-listener
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt-websocket-listener
      protocol: TCP
      port: 9001
      targetPort: 9001
