services:
  rabbitmq:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "1883:1883"
      - "5672:5672"
      - "9001:9001"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
networks:
  default:
    name: rabbitnet
    external: true