version: "3.9"
services:
  application:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - MONGOURI=${MONGOURI}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - MQTT_SERVER_HOST=mqtt-server-rabbitmq-1
      - MQTT_SERVER_PORT=5672
      - PROD_DEV_ENV=PROD_ENV
networks:
  default:
    name: rabbitnet
    external: true
