apiVersion: v1
kind: Service
metadata:
  name: web-user-auth-service
spec:
  type: LoadBalancer
  selector:
    app: web-user-auth
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
