version: "3.9"
services:
  node:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "5000:5000"
    environment:
      - MONGOURI=${MONGOURI}
      - PORT=5000
networks:
  default:
    name: rabbitnet
    external: true