apiVersion: v1
kind: Service
metadata:
  name: mqtt-client-auth-service
spec:
  type: LoadBalancer
  selector:
    app: mqtt-client-auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
